syncing sway config

diff --git a/.config/sway/wallpaper_switcher b/.config/sway/wallpaper_switcher
--- a/.config/sway/wallpaper_switcher
+++ b/.config/sway/wallpaper_switcher
@@ -1,20 +1,28 @@
 #!/bin/bash
 imagesdir=/home/nullproj/Pictures/wallpapers
-images=($(ls ${imagesdir} | egrep "jpg$|png$|jpeg"))
-rofi="rofi -dmenu"
-menu(){
+images=("${imagesdir}"/*.{jpg,png,jpeg})
+rofi="rofi -dmenu -p Select Wallpaper"
 
-    for i in ${!images[@]}; do
-            printf "${images[$i]}\n"
+menu() {
+    for image in "${images[@]}"; do
+        printf "%s\n" "$(basename "$image")"
     done
 }
+
 main() {
     choice=$(menu | ${rofi})
     if [[ -z $choice ]]; then return; fi
     killall swaybg
-    wal -i "$imagesdir/$choice"
-    swaybg -i "$imagesdir/$choice"
+    wal -i "${imagesdir}/${choice}"
+    swaymsg "output * bg ${imagesdir}/${choice} fill"
+    # swaybg -i "${imagesdir}/${choice}"
 }
+
+# Check if the directory exists
+if [ ! -d "$imagesdir" ]; then
+    echo "Error: Directory not found."
+    exit 1
+fi
 
 # Check if rofi is already running
 if pidof rofi >/dev/null; then
